version: "3.7"
services:
  sentilo-server:
    #  image: luismariotti1/sentilo
    build: sentilo
    container_name: sentilo_servers
    depends_on:
      - "mongo-server"
      - "redis-server"
    volumes:
      - sentilo_plataform:/sentilo

  mongo-server:
    image: luismariotti1/sentilo-mongo
    #  build: mongo
    container_name: sentilo_mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  redis-server:
    image: redis:4.0.11
    container_name: sentilo_redis
    command: redis-server --requirepass sentilo
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  # opentsdb-server:
  #   build: opentsdb
  #   image: luismariotti1/sentilo-opentsdb
  #   container_name: sentilo_opentsdb
  #   ports:
  #     - 4242:4242

  nginx-proxy:
    image: nginx:latest
    container_name: sentilo_nginx
    ports:
      - 443:443
      - 80:80
      - 8081:8081
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/:/etc/nginx/certs/
    depends_on:
      - "sentilo-server"

volumes:
  sentilo_plataform:
  mongo_data:
  mongo_config:
  redis_data:
    driver: local

networks:
  default:
    name: sentilo_network
    driver: bridge